server:
  port: 8085 
  
spring:   
  application:
   name: CONFIG-DEFAULT
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rahu313/MIcroServicesConfig
          clone-on-start: true
