server:
  port: 8085 
  
spring:   
  application:
   name: Config-Default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rahu313/MIcroServicesConfig
          clone-on-start: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      eurekaConnectionIdleTimeoutInSeconds: 30
      eurekaServerReadTimeoutSeconds: 30
      eurekaServerConnectTimeoutSeconds: 30
